#!/bin/bash

# Install Docker CE
sudo apt update
sudo apt --yes --no-install-recommends install \
    apt-transport-https \
    ca-certificates 
wget --output-document=- https://download.docker.com/linux/ubuntu/gpg \
    | sudo apt-key add - 
sudo add-apt-repository \
    "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu \
    $(lsb_release --codename --short) \
    stable"
sudo apt update
sudo apt --yes --no-install-recommends install docker-ce
sudo usermod --append --groups docker "$USER"
sudo systemctl enable docker

# Install Docker Compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose


