#!/bin/bash

# Scale application
docker-compose up -d --scale reserveroom=$1
docker-compose stop loadbalancer
docker-compose rm loadbalancer --force
docker-compose up -d --no-deps --build loadbalancer